version: '3.8'

services:

  # Drupal
  drupal:
    build: ./infra/drupal
    ports:
      - "80:8888"
    expose:
      - "8888"
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always
    environment:
      PROFILE: "standard"
    depends_on:
      - mysql

  # MySQL
  mysql:
    build: ./infra/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: _oYa*T=t09=Cc:KzsGcW
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: _oYa*T=t09=Cc:KzsGcW